[env:uno_r4_minima]
platform = renesas-ra
board = uno_r4_minima
framework = arduino
monitor_speed = 115200
build_flags =
    -O0
lib_deps =
    adafruit/DHT sensor library@^1.4.6
    paulstoffregen/OneWire@^2.3.8
    milesburton/DallasTemperature@^3.11.0

; ATmega2560 (Mega PRO / CH340): I2C en 20/21, TDS en A4 sin conflicto con SDA
[env:mega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/DHT sensor library@^1.4.6
    paulstoffregen/OneWire@^2.3.8
    milesburton/DallasTemperature@^3.11.0
    adafruit/RTClib@^2.1.4
