[env:uno_r4_minima]
platform = renesas-ra
board = uno_r4_minima
framework = arduino
monitor_speed = 115200
build_flags =
    -O0
lib_deps =
    adafruit/DHT sensor library@^1.4.6
    paulstoffregen/OneWire@^2.3.8
    milesburton/DallasTemperature@^3.11.0
    adafruit/RTClib@^2.1.4
